### ISSUE TITLE
rejecting incoming call does not hang up remote phone

### ISSUE THREAD

**Issue by fuchsnj** [bandwidthcom/bandwidth-webrtc#56] opened 2015-05-18 13:09 UTC
see https://github.com/inetCatapult/reg-ansible/issues/81

**Comment by wtcross** [comment] 2015-06-05 11:50
This is not an issue with `webrtc-client`. I'm going to close the issue and reopen in the edge repo.

**Comment by wtcross** [comment] 2015-06-05 11:54
On second thought, `webrtc-client` could help with the issue by always making a best effort to `unregister` the user on window unload (tab close, refresh). @fuchsnj, are you confident in the code that does that? I remember adding it at some point.

**Comment by wtcross** [comment] 2015-06-05 12:00
The issue occurs when there is more than one contact associated with a registered user. This happens (currently) if you refresh the page several times. The user is not unregistered before the page unloads.

**Comment by wtcross** [comment] 2015-06-05 12:01
[This](https://github.com/bandwidthcom/webrtc-client/blob/master/lib/BWClient.js#L9) code needs to be manually tested.

**Comment by wtcross** [comment] 2015-06-05 12:02
This is at least the third time an issue has popped up because of no real functional tests. We need those soon

**Comment by wtcross** [comment] 2015-06-05 12:06
If there is only one contact associated with your user then rejecting calls works. This is a stupid problem, I know. I'm fixing it upstream.

**Comment by wtcross** [comment] 2015-06-12 13:32
This issue has been resolved upstream. The behaviour was caused by an OpenSIPS registrar picking a `430 Flow Failed` reply from the outbound edge proxy that this client connects to. This reply is sent when a message is sent via a websocket connection that no longer exists.

**Closed by wtcross** 2015-06-12 13:32 UTC
Labels: blocker
